import { Lato, Open_Sans } from 'next/font/google'; 
import '@/styles/main.sass';
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700', '900'], variable: '--font-lato' });
const openSans = Open_Sans({ subsets: ['latin'], variable: '--font-open-sans' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className} ${openSans.variable} ${lato.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
